import { useEffect, useState } from 'react'
import { useOutletContext, Link } from 'react-router-dom'
import { BarChart } from '../components/Chart'
import { StatCard } from '../components/StatCard'
import { Status } from '../components/Status'
import { projectApi } from '../services/api'
import type { Project, Role } from '../types/domain'
type Context = { role: Role }
export function DashboardPage() {
  const { role } = useOutletContext<Context>(); const [items, setItems] = useState<Project[]>([])
  useEffect(() => { void projectApi.getProjects(role).then(setItems) }, [role])
  const active = items.filter((p) => p.status === 'ACTIVE').length; const completed = items.filter((p) => p.status === 'COMPLETED').length; const disputes = items.filter((p) => p.status === 'DISPUTED').length
  const submitted = items.flatMap((p) => p.milestones).filter((m) => m.status === 'SUBMITTED').length; const escrow = items.filter((p) => p.funded).reduce((n, p) => n + p.totalAmountEth, 0); const released = items.flatMap((p) => p.milestones).filter((m) => m.status === 'APPROVED').reduce((n, m) => n + m.amountEth, 0)
  const metrics = role === 'CLIENT' ? [['Projects created', items.length], ['Active projects', active], ['Funds in escrow', `${escrow} ETH`], ['Awaiting review', submitted], ['Open disputes', disputes]] : role === 'FREELANCER' ? [['Assigned projects', items.length], ['Active projects', active], ['Total earnings', `${released} ETH`], ['Awaiting client review', submitted], ['Open disputes', disputes]] : [['Open disputes', disputes], ['Resolved disputes', 0], ['Escrow under review', '3 ETH'], ['Projects involved', disputes], ['Recent decisions', 0]]
  return <><div className="page-intro"><div><h2>{role === 'CLIENT' ? 'Control your project escrow' : role === 'FREELANCER' ? 'Track work, submissions, and payments' : 'Resolve active payment disputes'}</h2><p>Role-specific demo data. Use the role selector to review all required flows.</p></div>{role === 'CLIENT' && <Link className="primary link-button" to="/projects/new">Create project</Link>}</div><div className="stats">{metrics.map(([label, value]) => <StatCard key={String(label)} label={String(label)} value={value as string | number} />)}</div>
  <div className="two-col"><BarChart title={role === 'ARBITRATOR' ? 'Open cases by status' : 'Milestone status distribution'} items={role === 'ARBITRATOR' ? [{ label: 'Open', value: disputes }, { label: 'Resolved', value: 0 }] : [{ label: 'Pending', value: items.flatMap((p) => p.milestones).filter((m) => m.status === 'PENDING').length }, { label: 'In progress', value: items.flatMap((p) => p.milestones).filter((m) => m.status === 'IN_PROGRESS').length }, { label: 'For review', value: submitted }, { label: 'Approved', value: items.flatMap((p) => p.milestones).filter((m) => m.status === 'APPROVED').length }]} /><section className="panel"><h3>Recent projects</h3><div className="compact-list">{items.slice(0, 3).map((p) => <Link to={`/projects/${p.id}`} key={p.id}><span><b>{p.title}</b><small>{p.id} · {p.totalAmountEth} ETH</small></span><Status value={p.status} /></Link>)}</div></section></div><div className="two-col"><BarChart title={role === 'ARBITRATOR' ? 'Escrow value by case' : 'Project funds by status'} items={role === 'ARBITRATOR' ? [{ label: 'Under review', value: 3, suffix: ' ETH' }, { label: 'Resolved', value: 0, suffix: ' ETH' }] : [{ label: 'Escrowed', value: escrow, suffix: ' ETH' }, { label: 'Released', value: released, suffix: ' ETH' }, { label: 'In dispute', value: items.filter((p) => p.status === 'DISPUTED').reduce((n, p) => n + p.totalAmountEth, 0), suffix: ' ETH' }]} /><BarChart title={role === 'CLIENT' ? 'Projects by outcome' : role === 'FREELANCER' ? 'Workload by project state' : 'Dispute decisions'} items={role === 'ARBITRATOR' ? [{ label: 'Release', value: 0 }, { label: 'Refund', value: 0 }] : [{ label: 'Active', value: active }, { label: 'Completed', value: completed }, { label: 'Disputed', value: disputes }]} /></div></>
}
