import { useEffect, useState } from 'react'
import { Link, useOutletContext, useParams } from 'react-router-dom'
import { MockTransactionButton } from '../components/MockTransactionButton'
import { Status, Toast } from '../components/Status'
import { projectApi } from '../services/api'
import type { Project, Role } from '../types/domain'
export function ProjectDetailPage() { const { id } = useParams(); const { role } = useOutletContext<{ role: Role }>(); const [project, setProject] = useState<Project>(); const [message, setMessage] = useState<string>(); const refresh = () => { if (id) void projectApi.getProject(id).then(setProject) }; useEffect(refresh, [id]); if (!project) return <p className="loading">Loading project…</p>
  const change = async (milestoneId: string, status: Project['milestones'][number]['status'], note?: string) => { await projectApi.updateMilestoneStatus(project.id, milestoneId, status, note); setMessage(`Mock state updated: milestone is now ${status}.`); refresh() }
  const accept = async () => { await projectApi.acceptProject(project.id); setMessage('Mock project accepted. Client can now fund the full escrow.'); refresh() }
  const fund = async () => { await projectApi.fundProject(project.id); setMessage('Mock funding confirmed: project is now ACTIVE. Real payment remains TODO(B).'); refresh() }
  const dispute = async (milestoneId: string) => { await projectApi.createDispute({ projectId: project.id, milestoneId, raisedBy: 'FREELANCER', description: 'Mock dispute created from the rejected milestone.' , amountEth: project.milestones.find((m) => m.id === milestoneId)?.amountEth ?? 0 }); setMessage('Mock dispute opened. The Arbitrator can now resolve it from Disputes.'); refresh() }
  return <><Link className="back" to="/projects">← Back to projects</Link><div className="detail-head"><div><p className="eyebrow">{project.id}</p><h2>{project.title}</h2><p>{project.description}</p></div><Status value={project.status} /></div><div className="stats"><StatBox label="Escrow" value={`${project.totalAmountEth} ETH`} /><StatBox label="Funding" value={project.funded ? 'Deposited' : 'Waiting'} /><StatBox label="Deadline" value={project.deadline} /></div><Toast message={message} />
  <section className="panel"><h3>Milestones</h3>{project.milestones.map((m) => <article className="milestone" key={m.id}><div><h4>{m.title} <Status value={m.status} /></h4><p>{m.description}</p><small>{m.amountEth} ETH · due {m.dueDate}</small>{m.submissionNote && <p className="note">Submission: {m.submissionNote}</p>}{m.rejectionReason && <p className="note">Rejection: {m.rejectionReason}</p>}</div><div className="actions">{role === 'CLIENT' && !project.funded && project.status === 'ACCEPTED' && <MockTransactionButton label="Fund full escrow" onComplete={() => void fund()} />}{role === 'CLIENT' && m.status === 'SUBMITTED' && <><MockTransactionButton label="Approve & release" onComplete={() => void change(m.id, 'APPROVED')} /><button onClick={() => void change(m.id, 'REJECTED', 'Please add the requested retention chart.')}>Reject (mock)</button></>}{role === 'FREELANCER' && project.status === 'CREATED' && <button className="primary" onClick={() => void accept()}>Accept project</button>}{role === 'FREELANCER' && (m.status === 'IN_PROGRESS' || m.status === 'REJECTED') && <button className="primary" onClick={() => void change(m.id, 'SUBMITTED', 'Mock submission evidence reference')}>{m.status === 'REJECTED' ? 'Resubmit milestone' : 'Submit milestone'}</button>}{m.status === 'REJECTED' && role === 'FREELANCER' && <button className="secondary" onClick={() => void dispute(m.id)}>Raise dispute (mock)</button>}</div></article>)}</section></> }
function StatBox({ label, value }: { label: string; value: string }) { return <section className="stat-card"><span>{label}</span><strong>{value}</strong></section> }
